### ISSUE TITLE
update public readme so that the auto add github action works for `api-client` and `github-action` tagged items

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/.github#2]
edit https://github.com/KittyCAD/.github/blob/main/profile/README.md
and edit the worfklow in that file to do the automation
https://github.com/KittyCAD/.github/blob/main/.github/workflows/auto-add-actions-and-client-libs.yml

**Comment by Irev-Dev** [comment]
Sorry might need a bit more a description for this, some kind of automation to do with our readme?

**Comment by hanbollar** [comment]
our [public facing readme](https://github.com/KittyCAD?view_as=public) has sections specifically to list available api-client libs and github actions we've created

i've tagged all our github repos for libs as `api-client` and for actions as `github-action` 
(feel free to change verbage of tags)

- `goal:` anytime we add a new action or api client lib with these tags, the public readme is auto populated with these additions
- `reasoning:` we're going to end up with so many of these it'll be cumbersome/annoying to manually keep that updated and in sync with our listing

i already started a bit on the automation (feel free to add on or just rewrite from scratch) - that's what's in the auto-add-actions-and-client-libs.yml

@Irev-Dev hope this clarifies ~ lmk if more info is needed tho

**Comment by Irev-Dev** [comment]
Resolved by https://github.com/KittyCAD/.github/pull/3 (checked it works committing straight to main https://github.com/KittyCAD/.github/commit/80f923b06a7920ea06178c70163c2f0a791467c3)

@hanbollar I uncommented the cron schedule, I assume that's what you wanted was it to run everyday?

I did end up rewriting, There was enough to this task that I didn't want to do it in bash.
I changed the format of the readme comments to `<!-- start-autogen-list tag=api-client -->` and the action grabs to tags from the readme then searches for repo with those tags, if we need to add a new list in future, the action won't need to be modified.

**Comment by hanbollar** [comment]
> @hanbollar I uncommented the cron schedule, I assume that's what you wanted was it to run everyday?

sounds good 👍  - whatever keeps it in sync without too much is best 

> 
> I did end up rewriting, There was enough to this task that I didn't want to do it in bash. I changed the format of the readme comments to `<!-- start-autogen-list tag=api-client -->` and the action grabs to tags from the readme then searches for repo with those tags, if we need to add a new list in future, the action won't need to be modified.

perf sounds good
